version: '3'

services:
  client:
    # build: ./client
    image: aminebenakil/mastermine-client
    command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build
    environment:
      - NODE_ENV=production
  mongodb:
    image: mongo:4.4.9
volumes:
  web-client-build:
