import { ProjectCardProps } from "./interfaces";

export const randomData: ProjectCardProps[] = [
  {
    projectName: "Master Mine",
    description: "An application for project management tool",
    projectManager: "John Doe",
    members: ["Jane Doe", "John Doe", "Lee sucks", "Leo The Cat"],
    progressBar: 30,
    creationDate: "21/11/2021",
  },
  {
    projectName: "Weary Traveler",
    description: "An application for traveling",
    projectManager: "Joe Dog",
    members: [
      "Betty Diaz",
      "Betty Harris",
      "Jessica Cooper",
      "Mary Garcia",
      "Patricia Moore",
    ],
    progressBar: 100,
    creationDate: "01/11/2021",
  },
  {
    projectName: "Track Moon",
    description: "An application to track the position of the Moon",
    projectManager: "Jesse The Cat",
    members: [
      "Jane Doe",
      "John Doe",
      "Lee sucks",
      "Leo The Cat",
      "John Williams",
      "Karen Ramirez",
      "Robert Henderson",
      "Betty Diaz",
    ],
    progressBar: 80,
    creationDate: "15/01/2022",
  },
  {
    projectName: "Track Mars",
    description: "An application to track the position of Mars",
    projectManager: "Poly Safe",
    members: [
      "Lee sucks",
      "Leo The Cat",
      "Karen Ramirez",
      "Sharon Roberts",
      "William Lee",
    ],
    progressBar: 75,
    creationDate: "10/03/2022",
  },
  {
    projectName: "Cat Mania",
    description: "A Cat's game",
    projectManager: "Tuty Fruity",
    members: [
      "Jane Doe",
      "John Doe",
      "Lee sucks",
      "Leo The Cat",
      "Linda Lewis",
      "William Collins",
      "Karen Ramirez",
    ],
    progressBar: 66,
    creationDate: "04/02/2022",
  },
  {
    projectName: "Cooker",
    description: "An application containing cooking recepies",
    projectManager: "Kate Kitycat",
    members: [
      "Jane Doe",
      "John Doe",
      "Lee sucks",
      "Leo The Cat",
      "Joe Regan",
      "Lisa Lopez",
      "John Williams",
      "Linda Lewis",
    ],
    progressBar: 23,
    creationDate: "15/06/2022",
  },
  {
    projectName: "Cars",
    description: "An application whish provide details about cars",
    projectManager: "Tuty Fruity",
    members: [
      "Kate Kitycat",
      "John Doe",
      "Lee sucks",
      "Leo The Cat",
      "Poly Safe",
      "Joe Dog",
      "Poly Safe",
    ],
    progressBar: 80,
    creationDate: "15/01/2022",
  },
  {
    projectName: "Dogs",
    description: "An application whish provide details about dogs",
    projectManager: "Doggy dog",
    members: ["Kate Kitycat", "Leo The Cat", "Poly Safe", "Poly Safe"],
    progressBar: 80,
    creationDate: "15/01/2022",
  },
];
